project:
  type: website
  preview:
    port: 3000
    browser: false

website:
  title: "Premios de la literatura española"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



