project:
  type: website
  preview:
    port: 3000
    browser: false

website:
  title: Premios de la Literatura Española
  search: false 
 
  navbar:
    collapse: false
    left: []
      
format:
  html:
    theme: 
    - flatly
    - styles.scss
    toc: true



