---
title: "Webgrafía"
---

<div class="nomain">
<ul>
<li><p>AGENCIAS (2022) Premio Planeta 2022, Las Provincias. Disponible en: <a href="https://www.lasprovincias.es/culturas/libros/dinero-premio-planeta-20221015100309-nt.html">https://www.lasprovincias.es/culturas/libros/dinero-premio-planeta-20221015100309-nt.html</a> (Accedido: 11 de abril de 2023).</p>
</li>
<li><p>Albacete, E. (2022) Curiosidades del Premio Nobel de Literatura que se entrega este jueves, niusdiario. Disponible en: <a href="https://www.niusdiario.es/cultura/libros/20221005/curiosidades-premio-nobel-literatura-entrega_18_07635412.html">https://www.niusdiario.es/cultura/libros/20221005/curiosidades-premio-nobel-literatura-entrega_18_07635412.html</a> (Accedido: 12 de abril de 2023).</p>
</li>
<li><p>Ganadores (sin fecha) Premioplaneta.es. Disponible en: <a href="https://www.premioplaneta.es/historia/ganadores.html">https://www.premioplaneta.es/historia/ganadores.html</a> (Accedido: 11 de abril de 2023).</p>
</li>
<li><p>Ibáñez, L. V. (2021) Carmen Laforet, escritora en el árido escenario del franquismo en España, La Izquierda Diario. Disponible en: <a href="https://www.izquierdadiario.es/Carmen-Laforet-escritora-en-el-arido-escenario-del-franquismo-en-Espana">https://www.izquierdadiario.es/Carmen-Laforet-escritora-en-el-arido-escenario-del-franquismo-en-Espana</a> (Accedido: 11 de abril de 2023).</p>
</li>
<li><p>López, A. (2022a) 5 curiosidades sobre el Premio Planeta que te sorprenderán, Planeta de Libros. Disponible en: <a href="https://www.planetadelibros.com/blog/actualidad/15/articulo/5-curiosidades-sobre-el-premio-planeta/299">https://www.planetadelibros.com/blog/actualidad/15/articulo/5-curiosidades-sobre-el-premio-planeta/299</a> (Accedido: 11 de abril de 2023).</p>
</li>
<li><p>López, A. (2022b) Premio Planeta 2022: todo lo que tienes que saber, Planeta de Libros. Disponible en: <a href="https://www.planetadelibros.com/blog/actualidad/15/efemerides/12/articulo/premio-planeta-todo-lo-que-necesitas-saber/453">https://www.planetadelibros.com/blog/actualidad/15/efemerides/12/articulo/premio-planeta-todo-lo-que-necesitas-saber/453</a> (Accedido: 11 de abril de 2023).</p>
</li>
<li><p>Nomination and selection of literature laureates (2018) Nobelprize.org. Disponible en: <a href="https://www.nobelprize.org/nomination/literature/">https://www.nobelprize.org/nomination/literature/</a> (Accedido: 12 de abril de 2023).</p>
</li>
<li><p>Premiados - Premio Cervantes (sin fecha) Gob.es. Disponible en: <a href="https://www.culturaydeporte.gob.es/premiado/busquedaPremioParticularAction.do?action=busquedaInicial&amp;params.id_tipo_premio=90&amp;layout=premioMiguelCervantesLibro&amp;cache=init&amp;language=es">https://www.culturaydeporte.gob.es/premiado/busquedaPremioParticularAction.do?action=busquedaInicial&amp;params.id_tipo_premio=90&amp;layout=premioMiguelCervantesLibro&amp;cache=init&amp;language=es</a> (Accedido: 11 de abril de 2023).</p>
</li>
<li><p>Presentación de los Premios Cervantes (sin fecha) Gob.es. Disponible en: <a href="https://www.culturaydeporte.gob.es/cultura/libro/premios/listado-de-premios/cervantes/presentacion.html">https://www.culturaydeporte.gob.es/cultura/libro/premios/listado-de-premios/cervantes/presentacion.html</a> (Accedido: 11 de abril de 2023).</p>
</li>
<li><p>Salas, C. (2013) Los datos más chocantes del Premio Planeta, La Información. Disponible en: <a href="https://www.lainformacion.com/opinion/carlos-salas/los-datos-mas-chocantes-del-premio-planeta/10681/">https://www.lainformacion.com/opinion/carlos-salas/los-datos-mas-chocantes-del-premio-planeta/10681/</a> (Accedido: 11 de abril de 2023).</p>
</li>
<li><p>Vives, J. (2023) Premio Nadal 2023: Todo lo que necesitas saber, Planeta de Libros. Disponible en: <a href="https://www.planetadelibros.com/blog/actualidad/15/articulo/premio-nadal-todo-lo-que-necesitas-saber/578">https://www.planetadelibros.com/blog/actualidad/15/articulo/premio-nadal-todo-lo-que-necesitas-saber/578</a> (Accedido: 11 de abril de 2023).</p>
</li>
<li><p>Wikipedia contributors (sin fecha) Premio Miguel de Cervantes, Wikipedia, The Free Encyclopedia. Disponible en: <a href="https://es.wikipedia.org/w/index.php?title=Premio_Miguel_de_Cervantes&amp;oldid=149952383">https://es.wikipedia.org/w/index.php?title=Premio_Miguel_de_Cervantes&amp;oldid=149952383</a>.</p>
</li>
<li><p>Wikipedia contributors (sin fecha) Premio Nadal, Wikipedia, The Free Encyclopedia. Disponible en: <a href="https://es.wikipedia.org/w/index.php?title=Premio_Nadal&amp;oldid=149229464">https://es.wikipedia.org/w/index.php?title=Premio_Nadal&amp;oldid=149229464</a>.</p>
</li>
<li><p>Wikipedia contributors (sin fecha) Premio Nobel, Wikipedia, The Free Encyclopedia. Disponible en: <a href="https://es.wikipedia.org/w/index.php?title=Premio_Nobel&amp;oldid=150119251">https://es.wikipedia.org/w/index.php?title=Premio_Nobel&amp;oldid=150119251</a>.</p>
</li>
<li><p>Wikipedia contributors (sin fecha) Premio Nobel de Literatura, Wikipedia, The Free Encyclopedia. Disponible en: <a href="https://es.wikipedia.org/w/index.php?title=Premio_Nobel_de_Literatura&amp;oldid=149229529">https://es.wikipedia.org/w/index.php?title=Premio_Nobel_de_Literatura&amp;oldid=149229529</a>.</p>
</li>
<li><p>Wikipedia, S. (2011) Premio Nadal: Escritores Ganadores del Premio Nadal, Miguel Delibes, Andres Trapiello, Fernando Arrabal, Francisco Umbral. Books.</p>
</li>
<li><p>ABC (sin fecha) Abc.es. Disponible en: <a href="https://www.abc.es/informacion/especial_pcervantes/index/historia.asp">https://www.abc.es/informacion/especial_pcervantes/index/historia.asp</a> (Accedido: 11 de abril de 2023).</p>
</li>
</ul>
</div>

<a role="button" class="btn btn-primary nolink"  href="../index.html"> Volver a la página principal</a>